@HostAddress = http://localhost:6600

POST {{HostAddress}}/product/
Content-Type: application/json

{ "Name": "Product A", "Description": "...", "Price": 5.25 }

###

POST {{HostAddress}}/product/
Content-Type: application/json

{ "Name": "Product B", "Description": "...", "Price": 7.00 }

###

GET {{HostAddress}}/product/
Accept: application/json

###