@HostAddress = http://localhost:6500

POST {{HostAddress}}/inventory/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YzJiZjczYy1kNDc0LTRiZWEtYmYyYS01YjkyZDZlOTQxODIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsicmVhZCIsIndyaXRlIl0sImV4cCI6NDkyNjgzOTA2NSwiaXNzIjoiRHVtbXkgaXNzdWVyIiwiYXVkIjoiTWlzY29uZmlndXJlZCJ9.rjlJfupV0X00NelBqFW9Sr9LtYd9GDSBGjY-9WXQmaM

{ "ProductId" : "75f5465c-2128-415f-874a-c97a9e393e51", "Quantity": 5 }

###
